require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/counterparties", type: :request do
  # Counterparty. As you add validations to Counterparty, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Counterparty.create! valid_attributes
      get counterparties_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      counterparty = Counterparty.create! valid_attributes
      get counterparty_url(counterparty)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_counterparty_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      counterparty = Counterparty.create! valid_attributes
      get edit_counterparty_url(counterparty)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Counterparty" do
        expect {
          post counterparties_url, params: {counterparty: valid_attributes}
        }.to change(Counterparty, :count).by(1)
      end

      it "redirects to the created counterparty" do
        post counterparties_url, params: {counterparty: valid_attributes}
        expect(response).to redirect_to(counterparty_url(Counterparty.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Counterparty" do
        expect {
          post counterparties_url, params: {counterparty: invalid_attributes}
        }.to change(Counterparty, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post counterparties_url, params: {counterparty: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested counterparty" do
        counterparty = Counterparty.create! valid_attributes
        patch counterparty_url(counterparty), params: {counterparty: new_attributes}
        counterparty.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the counterparty" do
        counterparty = Counterparty.create! valid_attributes
        patch counterparty_url(counterparty), params: {counterparty: new_attributes}
        counterparty.reload
        expect(response).to redirect_to(counterparty_url(counterparty))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        counterparty = Counterparty.create! valid_attributes
        patch counterparty_url(counterparty), params: {counterparty: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested counterparty" do
      counterparty = Counterparty.create! valid_attributes
      expect {
        delete counterparty_url(counterparty)
      }.to change(Counterparty, :count).by(-1)
    end

    it "redirects to the counterparties list" do
      counterparty = Counterparty.create! valid_attributes
      delete counterparty_url(counterparty)
      expect(response).to redirect_to(counterparties_url)
    end
  end
end
