require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/document_templates", type: :request do
  # DocumentTemplate. As you add validations to DocumentTemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DocumentTemplate.create! valid_attributes
      get document_templates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      document_template = DocumentTemplate.create! valid_attributes
      get document_template_url(document_template)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_document_template_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      document_template = DocumentTemplate.create! valid_attributes
      get edit_document_template_url(document_template)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DocumentTemplate" do
        expect {
          post document_templates_url, params: {document_template: valid_attributes}
        }.to change(DocumentTemplate, :count).by(1)
      end

      it "redirects to the created document_template" do
        post document_templates_url, params: {document_template: valid_attributes}
        expect(response).to redirect_to(document_template_url(DocumentTemplate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DocumentTemplate" do
        expect {
          post document_templates_url, params: {document_template: invalid_attributes}
        }.to change(DocumentTemplate, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post document_templates_url, params: {document_template: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested document_template" do
        document_template = DocumentTemplate.create! valid_attributes
        patch document_template_url(document_template), params: {document_template: new_attributes}
        document_template.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the document_template" do
        document_template = DocumentTemplate.create! valid_attributes
        patch document_template_url(document_template), params: {document_template: new_attributes}
        document_template.reload
        expect(response).to redirect_to(document_template_url(document_template))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        document_template = DocumentTemplate.create! valid_attributes
        patch document_template_url(document_template), params: {document_template: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested document_template" do
      document_template = DocumentTemplate.create! valid_attributes
      expect {
        delete document_template_url(document_template)
      }.to change(DocumentTemplate, :count).by(-1)
    end

    it "redirects to the document_templates list" do
      document_template = DocumentTemplate.create! valid_attributes
      delete document_template_url(document_template)
      expect(response).to redirect_to(document_templates_url)
    end
  end
end
